language: ruby
rvm:
  - 2.2.8
  - 2.3.6
  - 2.4.3
  - 2.5.0
cache: bundler
branches:
  only:
    - master
before_install: gem install bundler -v 1.15.4
script:
  - RSPEC_RETRIES=3 VERBOSE=1 bundle exec rake
